Exclude discussion about sprites and metasprites
gbdev/pandocs pull request #136
Opened 2021-02-16 18:40 UTC by AlvaroBurnett

Sprites and metasprites are software concepts. Since this document is about Game Boy hardware features (not game programming in general), I don't think that sprites and metasprites should be mentioned.

2021-02-18 09:07 UTC, ISSOtm requested changes
The point of this discussion was to clarify terminology commonly used; it's not strictly relevant to GB hardware, but the term "sprite" is largely misused in the more general gaming/programming community, including some meanings out of hardware scope.

So, while they're in theory out of scope for this document, as a GB programming introduction, I believe those *are* relevant.

2021-02-18 16:51 UTC, avivace commented
I agree with both of you. This kind of information is not related to GB and can add more confusion trying to explain those concepts. However they are important and commonly used and should be mentioned if we aim to provide something besides the bare hardware fundamentals.

Maybe we can move this information in a "info" box so it's separate from the rest but can still give some context?

2021-02-18 18:35 UTC, ISSOtm commented
Agreed—it might be useful, too, to mention in that box that the term "sprite" sees a lot of misuse in the more common language? (Don't we have a "disambiguation" box template, or am I misremembering?)

2021-02-19 12:32 UTC, ISSOtm approved these changes

2021-02-19 23:27 UTC, avivace approved these changes

2021-02-19 23:27 UTC, merged