Explain LCDC Status interrupt in a different way
gbdev/pandocs pull request #140
Opened 2021-02-17 04:07 UTC by AlvaroBurnett

2021-02-17 10:42 UTC, ISSOtm requested changes
As-is, this can't be accepted. The mechanism is fully understood, and the new explanation inserts some probability terms ("may not trigger", "usually goes right after").

If you didn't find the original description clear enough, we can work towards improving it.

On that topic, paging @LIJI32, as I know there are some subtleties that are not covered by this. (Mode 2...)

And finally, while we're editing this, can we rename "LCDC status interrupt" to either "LCD status interrupt" or "STAT interrupt"? `LCDC` has absolutely *nothing* to do with it, so the name's more confusing than anything else.

2021-02-17 11:20 UTC, AlvaroBurnett commented
I said "may not trigger" and "usually goes right after" because sometimes there is a Mode 1 between the Mode 0 and Mode 2. If we made the example for Mode 2 and Mode 3 instead, then there wouldn't be any doubt that one goes always right after the other.

2021-02-17 14:49 UTC, avivace requested changes

2021-02-17 14:49 UTC, avivace commented on content/Video_Display.md
> +the LY=LYC interrupt will not trigger unless we are lucky and there is a Mode 1
`unless we are lucky` seems very out of context here. Maybe `unless a Mode 1 happens` but it'll need some rephrasing specifying the once per frame thing.

2021-02-18 09:03 UTC, ISSOtm requested changes
I see that you're trying to turn technical descriptions into something more "noob-friendly".

I'm neither for nor against it *per se*, but this begs the more general question of whether we want Pan Docs to be "user-friendly" descriptions, or more technical ones. I guess e.g. [gb-ctr](https://github.com/Gekkio/gb-ctr) could serve the latter purpose, and Pan Docs the former.

I just think that then, we should make sure that any technical information reworded out of Pan Docs is present elsewhere.

2021-02-19 12:40 UTC, ISSOtm approved these changes

2021-02-19 12:40 UTC, ISSOtm commented on content/Video_Display.md
> +As we saw in the description of the STAT register, the LCD Controller cycles
Maybe this should be turned into a warning box? It's a behavior that may surprise people, after all.

2021-02-19 12:40 UTC, ISSOtm commented on content/Video_Display.md
> +### FF41 - STAT (R/W)
"LCD status" or "PPU status" should be a fitting description.

2021-02-19 12:40 UTC, ISSOtm commented
(Oops, misclick, I meant to "Changes requested".)

2021-02-19 13:59 UTC, ISSOtm approved these changes

2021-02-19 23:23 UTC, avivace approved these changes

2021-02-19 23:23 UTC, merged