tile data - fix language and number notation
gbdev/pandocs pull request #183
Opened 2021-02-21 19:40 UTC by AlvaroBurnett

2021-02-22 10:39 UTC, ISSOtm requested changes

2021-02-22 10:39 UTC, ISSOtm commented on content/Video_Display.md
>  Byte 0-1  First Line (Upper 8 pixels)
Maybe "topmost"?

2021-02-22 10:39 UTC, ISSOtm commented on content/Video_Display.md
> +bit 0 the rightmost. For example : let's say you have \$57 \$36 (in
No spaces before colons, please

2021-02-22 11:19 UTC, AlvaroBurnett commented on content/Video_Display.md
>  Byte 0-1  First Line (Upper 8 pixels)
Fixed

2021-02-22 11:19 UTC, AlvaroBurnett commented on content/Video_Display.md
> +bit 0 the rightmost. For example : let's say you have \$57 \$36 (in
Fixed

2021-02-25 04:10 UTC, ISSOtm approved these changes

2021-02-25 04:10 UTC, ISSOtm commented
Needs rebase + extra review

2021-02-25 07:19 UTC, AlvaroBurnett commented
Rebased

2021-02-28 20:18 UTC, ISSOtm approved these changes

2021-02-28 20:23 UTC, merged