LCDC names
gbdev/pandocs pull request #188
Opened 2021-02-22 15:58 UTC by AlvaroBurnett

2021-03-05 13:46 UTC, ISSOtm requested changes

2021-03-05 13:46 UTC, ISSOtm commented on content/LCDC.md
> +## LCDC.6 - Window tile map range
Range or area?

2021-03-05 13:52 UTC, AlvaroBurnett commented on content/LCDC.md
> +## LCDC.6 - Window tile map range
Yes, area is better. Fixed

2021-03-05 13:56 UTC, ISSOtm commented on content/LCDC.md
> +## LCDC.6 - Window tile map range
Lines 58 and 67 too, please

2021-03-05 14:16 UTC, AlvaroBurnett commented on content/LCDC.md
> +## LCDC.6 - Window tile map range
Fixed

2021-03-05 14:18 UTC, ISSOtm approved these changes

2021-03-07 02:29 UTC, avivace approved these changes

2021-03-07 02:29 UTC, merged