MBC5
gbdev/pandocs pull request #252
Opened 2021-03-11 01:16 UTC by AlvaroBurnett

2021-03-12 22:46 UTC, ISSOtm requested changes

2021-03-12 22:46 UTC, ISSOtm commented on content/MBC5.md
> +writing to external RAM. Writing $00 will disable it.
```suggestion
writing to external RAM. Writing $00 will disable it.

Actual MBCs actually enable RAM when writing any value whose bottom 4 bits equal $A (so $0A, $1A, and so on), and disable it when writing anything else.
Relying on this behavior is not recommended for compatibility reasons.
```

2021-03-13 05:29 UTC, AlvaroBurnett commented
Applied the requested change, but GitHub complains about a bunch of things that seem unrelated to this change.

2021-03-13 11:08 UTC, ISSOtm approved these changes
They are unrelated indeed, they come from the checks introduced by #172; since this change doesn't introduce any new errors, it's fine.

2021-03-14 09:38 UTC, avivace approved these changes

2021-03-14 18:27 UTC, merged