Slight rewording of "Writing Data to OAM Memory" to clarify DMA instructions
gbdev/pandocs pull request #305
Opened 2021-06-26 06:15 UTC by TheRektafire

2021-06-26 19:30 UTC, avivace approved these changes

2021-06-27 16:03 UTC, ISSOtm requested changes

2021-06-27 16:03 UTC, ISSOtm commented on src/OAM.md
> +The recommended method is to write the data to normal RAM first, then copy that RAM to OAM by using the DMA transfer function, initiated by writing the high byte of the RAM page on which the data is
Clarifying that "normal RAM" means WRAM or SRAM may be better.

2021-06-27 16:03 UTC, ISSOtm commented on src/OAM.md
> +The recommended method is to write the data to normal RAM first, then copy that RAM to OAM by using the DMA transfer function, initiated by writing the high byte of the RAM page on which the data is
We don't usually talk about "RAM page", so this term must not be used.
Suggested: "... by writing the high byte of the address, which must be a multiple of $100, to..."

2021-06-27 16:03 UTC, ISSOtm commented on src/OAM.md
> +The recommended method is to write the data to normal RAM first, then copy that RAM to OAM by using the DMA transfer function, initiated by writing the high byte of the RAM page on which the data is
Please break the line at the end of the sentence, i.e. before the "While".

2021-07-20 07:11 UTC, ISSOtm commented
No activity for a while, should we apply the modifications ourselves?

2021-08-01 11:38 UTC, ISSOtm commented
PR seems inactive, I'll be applying the changes myself and merging.

2021-08-01 12:13 UTC, ISSOtm approved these changes

2021-08-01 12:15 UTC, merged