Cleanup of MBC1 docs
gbdev/pandocs pull request #312
Opened 2021-07-09 19:35 UTC by TheThief

2021-07-15 08:21 UTC, TheThief commented on src/MBC1.md
> +In its default configuration MBC1 supports up to 512 kiBytes ROM with up to 32 kiBytes of banked RAM. Some cartridges utilize an alternative wiring where the 2-bit RAM banking register is wired as an
https://github.com/gbdev/pandocs/pull/310#discussion_r669921583

TODO: Add a section for the large rom wiring so that the MMM01 docs can link to it

2021-07-15 18:35 UTC, ISSOtm commented
I already begun a partial review some time ago, but I don't want to continue it before #317 is merged.

2021-09-04 15:44 UTC, ISSOtm commented
Begun another partial review, but the mapping diagrams are basically blocked by #334.

2021-09-04 17:44 UTC, avivace commented
Any update on this @ISSOtm ?

2021-09-04 17:46 UTC, ISSOtm commented
I haven't worked on this (been busy on other PRs, as you know), but upstream has noted some fixes of their own, anyway.

2022-01-07 22:26 UTC, avivace approved these changes

2022-01-07 22:30 UTC, ISSOtm requested changes

2022-01-08 08:33 UTC, TheThief commented on src/MBC1.md
> +In its default configuration MBC1 supports up to 512 kiBytes ROM with up to 32 kiBytes of banked RAM. Some cartridges utilize an alternative wiring where the 2-bit RAM banking register is wired as an
Common misconception, but no. The 2 bit register directly outputs on MBC pins, and is physically wired to ROM or RAM by the cart depending on which needs it.

2022-05-02 08:33 UTC, avivace approved these changes

2022-05-02 16:41 UTC, merged