Update SGB_Command_Multiplayer.md
gbdev/pandocs pull request #352
Opened 2021-09-05 22:20 UTC by CasualPokePlayer

Testroms indicate that writing $30 to joyp is unneeded for incrementing the joypad count, and the "cancelling" behavior described does not happen in reality (nor does Yellow seem to rely on such behavior). One game (Gamera - Daikaijuu Kuuchuu Kessen) appears to rely on a P15 LOW to HIGH incrementing the joypad number and not the $30 write.

[sgb-mlt-test.zip](https://github.com/mgba-emu/mgba/files/7112150/sgb-mlt-test.zip)
https://github.com/CasualPokePlayer/test-roms/blob/sgb-mlt-test/src/intro.asm

(note, only the top 2 lines have been verified so far, which is enough to confirm this cancelling behavior doesn't really happen (the behavior described is done poorly anyways ("then LOW again... it cancels the increment until P15 is lowered again" you can't lower something already lowered, so what?))

2021-09-05 22:58 UTC, ISSOtm requested changes

2021-09-05 22:58 UTC, ISSOtm commented on src/SGB_Command_Multiplayer.md
> +Next, read joypad state normally. The joypad number count is automatically incremented (or restarted if the last joypad is reached) by P15 going LOW to HIGH, so you can simply repeat reading the joyp
```suggestion
Next, read joypad state normally.
The next joypad is automatically selected when P15 goes from LOW (0) to HIGH (1), so you can simply repeat reading the joypad state normally until all two (or four) joypads have been read out.
```

2021-09-05 23:11 UTC, ISSOtm requested changes

2021-09-05 23:11 UTC, ISSOtm commented on src/SGB_Command_Multiplayer.md
> +The next joypad is automatically selected when P15 goes from LOW (0) to HIGH (1), so you can simply repeat reading the joypad state normally until all two (or four) joypads have been read out.
```suggestion
The next joypad is automatically selected when P15 goes from LOW (0) to HIGH (1) ([source](https://github.com/CasualPokePlayer/test-roms/blob/sgb-mlt-test/src/intro.asm)), so you can simply repeat reading the joypad state normally until all two (or four) joypads have been read out.
```

2021-09-05 23:12 UTC, ISSOtm approved these changes

2021-09-06 07:23 UTC, avivace approved these changes

2021-09-06 07:24 UTC, merged