Clarifications to the explanation of interrupts
gbdev/pandocs pull request #417
Opened 2022-06-08 17:15 UTC by ihonen

I noticed that some of the language used in the explanation of interrupts was vague and not technically entirely correct, so I thought I'd contribute a revision.

For example:

- an interrupt is not executed, it is serviced
- the interrupt vector is not the same thing as the interrupt handler
- etc.

Mostly rather insignificant, I know, but I couldn't help my pedantic self.

2022-06-08 17:50 UTC, avivace approved these changes
Thanks a lot! I really like the "execution -> servicing" change.

2022-06-08 21:28 UTC, ISSOtm requested changes
Thank you! This is much better.

2022-06-08 21:28 UTC, ISSOtm commented on src/Interrupts.md
> +Where \<ISR\> is the interrupt service routine that is automatically executed
```suggestion
Where \<ISR\> is the Interrupt Service Routine that is automatically executed
```

2022-06-08 21:28 UTC, ISSOtm commented on src/Memory_Map.md
> +program doesn't use any (or only some) `rst` instructions or interrupts. `rst`
```suggestion
program doesn't use any (or only some) [`rst`](https://rgbds.gbdev.io/docs/v0.5.2/gbz80.7/#RST_vec) instructions or interrupts. `rst`
```

2022-06-09 19:42 UTC, merged

2022-06-12 15:05 UTC, ihonen commented
A bit late with my response, but glad you liked it!