Converted sections 2.2.6 - 3.1.2
gbdev/pandocs pull request #467
Opened 2023-01-22 03:20 UTC by ApianbelleDev

I'm nowhere close to done, but I wanted to at least open a PR with what I _do_ have, as to hopefully get feedback and merge with what's already there. as for the entire thing, please be patient as I'm working as quickly as I can, and I'd appreciate feedback with what I can do better.

2023-02-06 21:32 UTC, avivace commented on src/Gameboy_Camera.md
> +The Game Boy Camera cartridge is one of the few cartridges that use the PHI signal (clock from the GB). That signal is a 1MHz clock (1047567 Hz). the M6438FP chip needs a clock input too, which is ha
```suggestion
The Game Boy Camera cartridge is one of the few cartridges that use the PHI signal (clock from the GB). That signal is a 1MHz clock (1047567 Hz). the M6438FP chip needs a clock input too, which is half the frequency of the PHI pin (0.5Mhz, 524288Hz). The reason for that is that the sensor chip sometimes handles the signals on the rising edge of the clock, but other times on the falling edge.
```

2023-03-28 17:06 UTC, ISSOtm requested changes
Here are a bunch of editorial tweaks. Thank you for taking the time!

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +the M64282FP does some processing to the captured image. First, it performs an edge control, then it does gain controll, and lastly, it deas level control. the resulting analog value is the one that
```suggestion

The M64282FP does some processing to the captured image.
First, it performs an edge control, then it does gain control, and lastly, it does level control.
The resulting analog value is the one that can be read in the V<sub>out</sub> pin.
The sensor can capture infrared radiation, so the images can be a bit strange compared to others captured by better sensors.

```

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +This corresponds to the register A001 of the Game Boy Camera. When shooting, the values change based on how much light there is.
```suggestion

This corresponds to the register $A001 of the Game Boy Camera.
When shooting, the values change based on how much light there is.
```

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +
```suggestion
```

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +If G4 = "1", the total gain is the previous one plus 6dB. The Game Boy Camera uses 00h, 04h, 08h, and 0Ah at 14.0dB, 20.0dB, 26.0dB, and 32dB respectively, which translate to a gain of 5.01, 10.00, 1
```suggestion
If G4 = "1", the total gain is the previous one plus 6 dB.
The Game Boy Camera uses $00, $04, $08, and $0A at 14 dB, 20 dB, 26 dB, and 32 dB respectively, which translate to a gain of 5.01, 10.00, 19.95, and 39.81.
The Game Boy Camera seems to like to duplicate the game in each step.

```

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +Registers 2 and 3 contain the exposure time(a 16 bit unsigned value). According to the M64282FP datasheet, each step is 16 µs. the GB needs 16 PHI clocks for every step. However, if N = "1", exposure
```suggestion

Registers 2 and 3 contain the exposure time (a 16 bit unsigned value).
According to the M64282FP datasheet, each step is 16 µs.
The GB needs 16 PHI clocks for every step.
However, if N = "1", `exposure_steps` should be greater than or equal to $0030.
```

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +    Step time = 1 / 1048576 Hz * 16 = 0,954 µs* 16 = 15,259 µs
```suggestion
u16 exposure_steps ((Reg2) << 8) | [Reg3]
Step time = 1 / 1048576 Hz * 16 = 0,954 µs* 16 = 15,259 µs
```
I'm not entirely sure about the parens vs. brackets on the two registers?

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +It's a bit less than the 16 µs the datasheet says, but it's close enough. below are some example values to get acceptable pictures under various light conditions
```suggestion

It's a bit less than the 16 µs the datasheet says, but it's close enough. 
Below are some example values to get acceptable pictures under various light conditions:
```

2023-03-28 17:06 UTC, ISSOtm commented on src/Gameboy_Camera.md
> +| F000h | Room at night with only a TV on in the background.    |
```suggestion
| $0030 | Objects under direct sunlight.                        |
| $0300 | Objects not under direct sunlight.                    |
| $0800 | Room during the day with good light.                  |
| $2C00 | Room at night with no light.                          |
| $5000 | Room at night with no light, only a reading lamp .    |
| $F000 | Room at night with only a TV on in the background.    |
```

2023-04-08 23:30 UTC, avivace commented
Replaced by https://github.com/gbdev/pandocs/pull/478

2023-04-08 23:30 UTC, closed without merging