Move ly lyc to stat page
gbdev/pandocs pull request #469
Opened 2023-01-24 11:54 UTC by leinacc

Closes https://github.com/gbdev/pandocs/issues/439

I decided on putting these on top of STAT as they're mentioned in sentence 2 of STAT's description, so it's fresh info

Maybe title needs changing? Though LCD Status Registers feels wrong

2023-01-24 14:19 UTC, avivace commented on src/STAT.md
> +## FF44 — LY: LCD Y coordinate \[read-only\]
I think in any case they should be after the terminology box, as it's meant to be an introductory block or text to satisfy so me knowledge pre-requirements

2023-01-28 20:16 UTC, ISSOtm requested changes
I dunno, "LCD status registers" seems fine to me, since they are multiple registers that report the PPU's drawing status.

That said, the name in `SUMMARY.md` should also be changed, then.

2023-01-28 20:16 UTC, ISSOtm commented on src/STAT.md
> +The Game Boy permanently compares the value of the LYC and LY registers.
```suggestion
The Game Boy constantly compares the value of the LYC and LY registers.
```

2023-01-29 01:10 UTC, ISSOtm commented
That last commit is indeed a good idea, but then I'm thinking we may want to actually introduce and link to a new section at the bottom to specifically the explanation of the LCD modes. What do you think?

2023-01-29 01:35 UTC, leinacc commented
> That last commit is indeed a good idea, but then I'm thinking we may want to actually introduce and link to a new section at the bottom to specifically the explanation of the LCD modes. What do you think?

It sounds like a good idea just seeing those other pages link to STAT by mentioning modes.
I'll place the header above `The LCD controller operates on a 2^22 Hz = 4.194 MHz dot clock.` where it starts to describe them

2023-03-08 12:21 UTC, avivace approved these changes

2023-03-14 22:26 UTC, ISSOtm approved these changes

2023-03-14 22:27 UTC, merged

2023-03-14 22:27 UTC, ISSOtm commented
Thank you!