add footnote about real DMG clock speed
gbdev/pandocs pull request #475
Opened 2023-03-27 19:29 UTC by jkotlinski

Add footnote that DMG typically runs 50-70 PPM slower than specified.

2023-03-27 20:46 UTC, avivace approved these changes

2023-03-28 16:54 UTC, ISSOtm requested changes
Hmm, this should be checked on MGB, maybe the drift is different there. Or at least, it should be mentioned that their status is unknown?

2023-03-28 18:15 UTC, jkotlinski commented
Unfortunately, I do not have an MGB. I updated the text accordingly.

2023-03-29 21:58 UTC, avivace approved these changes

2023-03-29 21:58 UTC, avivace commented on src/Specifications.md
> +Real DMG units tend to run about 50-70 PPM slow. Accuracy of other models is unknown. [See this page](https://github.com/jkotlinski/gbchrono) for more details.
```suggestion
Real DMG units tend to run about 50-70 PPM slower. Accuracy of other models is unknown. [See this page](https://github.com/jkotlinski/gbchrono) for more details.
```

2023-03-29 22:20 UTC, jkotlinski commented
Not sure I follow this edit, it is normal language to say that a watch is
running slow.

ons 29 mars 2023 kl. 23:59 skrev Antonio Vivace ***@***.***>:

> ***@***.**** approved this pull request.
> ------------------------------
>
> In src/Specifications.md
> <https://github.com/gbdev/pandocs/pull/475#discussion_r1152524315>:
>
> > @@ -58,6 +58,9 @@ td:first-child {
>    </tbody>
>  </table>
>
> +[^dmg_clk]:
> +Real DMG units tend to run about 50-70 PPM slow. Accuracy of other models is unknown. [See this page](https://github.com/jkotlinski/gbchrono) for more details.
>
> ⬇️ Suggested change
>
> -Real DMG units tend to run about 50-70 PPM slow. Accuracy of other models is unknown. [See this page](https://github.com/jkotlinski/gbchrono) for more details.
> +Real DMG units tend to run about 50-70 PPM slower. Accuracy of other models is unknown. [See this page](https://github.com/jkotlinski/gbchrono) for more details.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gbdev/pandocs/pull/475#pullrequestreview-1364024909>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAY34OYBLVFVRZDUNR5FTODW6SWCNANCNFSM6AAAAAAWJSBAAA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-30 06:15 UTC, merged