Switch Twitter link to some Nitter instance
gbdev/pandocs pull request #489
Opened 2023-06-21 22:14 UTC by ISSOtm

This kind of reverts 3f1c43e, since now we'll know if that link goes down. Twitter cannot be used, since like that commit mentions, Twitter now blocks automation (thanks to a certain Elongated Muskrat), which includes mdbook-linkcheck.

The choice of Nitter instance is motivated by a few points. First, a list of instances is available from Nitter's GitHub wiki (https://github.com/zedeus/nitter/wiki/Instances).

The first parameter in the choice is the region; there are three (3) "anycast" instances, which may (1) reduce latency for readers of Pan Docs, and (2) reduce the load of Pan Docs' link-checking itself (by distributing across several servers behind the anycast). I think, anyway.

One of these instances is not updated, which is not a good sign for reliability either.

Then, it turns out several instances block HTTP HEAD requests like Twitter (but not GET, suggesting it is intentional); of the remaining two, only the chosen one doesn't.

2023-06-21 22:22 UTC, ISSOtm commented
Right, I forgot to mention this: I also considered https://twiiit.com/, but unfortunately, some of the instances I got in my testing had badly configured TLS, and others blocked HEAD requests; hence picking a known-good one instead.

2023-06-23 22:01 UTC, avivace commented
What about https://web.archive.org/web/20220131221108/https://twitter.com/CasualPkPlayer/status/1409752977812852736 ?

2023-06-23 22:02 UTC, avivace requested changes

2023-06-23 22:02 UTC, avivace commented on src/Power_Up_Sequence.md
> +[Different models tend to exhibit different patterns](https://notabird.site/CasualPkPlayer/status/1409752977812852736), but they are random nonetheless, even depending on factors such as the ambient
```suggestion
[Different models tend to exhibit different patterns](https://web.archive.org/web/20220131221108/https://twitter.com/CasualPkPlayer/status/1409752977812852736), but they are random nonetheless, even depending on factors such as the ambient temperature.
```

2023-06-24 07:54 UTC, merged