Fix some typos & inconsistencies in Licensees
gbdev/pandocs pull request #549
Opened 2024-05-06 15:17 UTC by IsaacMarovitz

There are likely still some typos and mistakes here, and there are some companies I've not been able to hunt down that are listed here, like `lozc`, and `Entertainment i`

2024-05-06 15:32 UTC, ISSOtm commented on src/The_Cartridge_Header.md
> +B1    | ASCII Corportation or Nexsoft
```suggestion
B1    | ASCII Corporation or Nexsoft
```

2024-05-06 15:33 UTC, ISSOtm requested changes
Thank you! That's a good quality improvement.

Do you have a source for those? It would be nice to be able to have some references, and (Wikipedia?) links would be a plus, even.

2024-05-06 16:22 UTC, IsaacMarovitz commented
> Do you have a source for those? It would be nice to be able to have some references, and (Wikipedia?) links would be a plus, even.

As far as I can tell, this information was initially sourced from SephirothBCH's contribution on the gbdev wiki all the way back in 2000. I'm not sure where they got the original list from, and that list shares many of the issues present here.

2024-05-06 16:24 UTC, IsaacMarovitz commented
For companies that underwent renames, should those be listed somewhere here?

2024-05-06 16:32 UTC, ISSOtm commented
> For companies that underwent renames, should those be listed somewhere here?

Preferably. I'm thinking of using footnotes for that:

```md
- `xy`: [FooBar Interactive](//en.wikipedia.org/wiki/FooBar_Interactive)[^foobar]

<!-- And at the bottom of the page... -->

[^foobar]: Known as [Frobble Limited](//en.wikipedia.org/wiki/Frobble_Limited) since 2013.

```

> I can also provide links to each company's Wikipedia page (if they exist) if that's easier.

IMO, having both would be ideal.

2024-05-07 07:07 UTC, avivace approved these changes

2024-05-07 23:19 UTC, ISSOtm approved these changes
Outstanding work, thank you very much!!

2024-05-07 23:20 UTC, merged