Clarify palettes bootrom behavior
gbdev/pandocs pull request #576
Opened 2024-10-30 22:59 UTC by alloncm

I find the lack of a reference to the boot up sequence and the statement about the bootrom setting the object palettes confusing.

Also update `DEPLOY.md` recommended python version

2024-11-04 08:24 UTC, avivace requested changes

2024-11-04 08:24 UTC, avivace commented on src/Palettes.md
> +For most of the cases the boot ROM leaves all object colors uninitialized (and thus somewhat random),
```suggestion
For most of the cases the boot ROM leaves all object colors uninitialized (and thus somewhat random/unreliable),
```

2024-11-04 19:31 UTC, avivace approved these changes

2024-11-04 22:08 UTC, ISSOtm requested changes

2024-11-07 07:54 UTC, avivace approved these changes

2024-11-09 21:07 UTC, ISSOtm requested changes
Thank you! The content looks good, I have just one last nitpick, and then we should be good to merge :)

2024-11-09 21:07 UTC, ISSOtm commented on src/Palettes.md
> +used by OBP0/OBP1, for more [see](./Power_Up_Sequence.md#compatibility-palettes).
```suggestion
used by OBP0/OBP1, [as explained here](<#Compatibility palettes>).
```

Improving the link text slightly, and also we have a plugin that converts the section's name into an appropriate link.

2024-11-09 21:27 UTC, ISSOtm approved these changes
Thank you!

2024-11-09 21:28 UTC, merged