Add behavior of the HDMA HBlank mode in halt mode
gbdev/pandocs pull request #577
Opened 2024-11-01 11:37 UTC by alloncm

2024-11-02 21:10 UTC, ISSOtm approved these changes
I have seen this confirmed several times, so I'm approving this despite the lack of a reference. (Better have the information *somewhere*!)

Thank you!

2024-11-02 21:59 UTC, alloncm commented
I can add a reference to a test ROM I wrote. 
The issue with it is that it doesn't verify the transfer continues once the CPU is unhalted (that's why I didn't add it in this PR). 
I verified this behavior manually with SameBoy though.

https://github.com/alloncm/MagenTests?tab=readme-ov-file#vram-dma-hblank-mode

2024-11-02 22:56 UTC, avivace approved these changes
OK for me in this state but I'd add the link to the test rom

2024-11-02 22:58 UTC, avivace requested changes
e.g. like this

2024-11-02 22:58 UTC, avivace commented on src/CGB_Registers.md
> +the transfer will also be halted and will be resumed only when the CPU resumes execution.
```suggestion
the transfer will also be halted and will be resumed only when the CPU resumes execution ([test rom](https://github.com/alloncm/MagenTests?tab=readme-ov-file#vram-dma-hblank-mode) exhibiting this behaviour)
```

2024-11-03 22:37 UTC, avivace approved these changes

2024-11-03 22:38 UTC, merged